[build]
  base = "frontend"        # your React app folder
  publish = "frontend/build"
  command = "npm run build"

# Fix React routing (VERY IMPORTANT)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200